/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        vault: {
          surface: "#fbf9f5",
          "surface-dim": "#dbdad6",
          "surface-bright": "#fbf9f5",
          "surface-container-lowest": "#ffffff",
          "surface-container-low": "#f5f3ef",
          "surface-container": "#efeeea",
          "surface-container-high": "#eae8e4",
          "surface-container-highest": "#e4e2de",
          "on-surface": "#1b1c1a",
          "on-surface-variant": "#4f4540",
          "inverse-surface": "#30312e",
          "inverse-on-surface": "#f2f0ed",
          outline: "#81756f",
          "outline-variant": "#d3c3bd",
          "surface-tint": "#705a4f",
          primary: "#25160e",
          "on-primary": "#ffffff",
          "primary-container": "#3c2a21",
          "on-primary-container": "#aa9084",
          "inverse-primary": "#dec1b3",
          secondary: "#775a19",
          "on-secondary": "#ffffff",
          "secondary-container": "#fed488",
          "on-secondary-container": "#785a1a",
          tertiary: "#0c1c1c",
          "on-tertiary": "#ffffff",
          "tertiary-container": "#213131",
          "on-tertiary-container": "#889999",
          error: "#ba1a1a",
          "on-error": "#ffffff",
          "error-container": "#ffdad6",
          "on-error-container": "#93000a",
          "primary-fixed": "#fbdcce",
          "primary-fixed-dim": "#dec1b3",
          "on-primary-fixed": "#281810",
          "on-primary-fixed-variant": "#574238",
          "secondary-fixed": "#ffdea5",
          "secondary-fixed-dim": "#e9c176",
          "on-secondary-fixed": "#261900",
          "on-secondary-fixed-variant": "#5d4201",
          "tertiary-fixed": "#d4e6e5",
          "tertiary-fixed-dim": "#b8cac9",
          "on-tertiary-fixed": "#0e1e1e",
          "on-tertiary-fixed-variant": "#394a4a",
          background: "#fdfbf7",
          "on-background": "#1b1c1a",
          "surface-variant": "#e4e2de",
          "surface-soft": "#f5f0e6",
          "surface-muted": "#e5ded0",
          "text-secondary": "#6d5d51",
          "ink-black": "#1a1412",
          ochre: "#c5a059",
          "ochre-hover": "#b08d48",
          "gold-accent": "#c5a059",
          "board-wood": "#8b5a2b",
          "board-cream": "#f0d9b5",
        },
      },
      fontFamily: {
        display: ['"Libre Caslon Text"', "Georgia", "serif"],
        body: ["Karla", "Arial", "sans-serif"],
      },
      borderRadius: { vault: "0.25rem" },
      maxWidth: { content: "1120px" },
    },
  },
  plugins: [],
};
