/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        vault: {
          surface: "#111317",
          "surface-dim": "#111317",
          "surface-bright": "#37393e",
          "surface-container-lowest": "#0c0e12",
          "surface-container-low": "#1a1c20",
          "surface-container": "#1e2024",
          "surface-container-high": "#282a2e",
          "surface-container-highest": "#333539",
          "on-surface": "#e2e2e8",
          "on-surface-variant": "#d1c5b4",
          "inverse-surface": "#e2e2e8",
          "inverse-on-surface": "#2f3035",
          outline: "#9a8f80",
          "outline-variant": "#4e4639",
          "surface-tint": "#e9c176",
          primary: "#e9c176",
          "on-primary": "#412d00",
          "primary-container": "#c5a059",
          "on-primary-container": "#4e3700",
          "inverse-primary": "#775a19",
          secondary: "#c2c6d4",
          "on-secondary": "#2b303b",
          "secondary-container": "#444954",
          "on-secondary-container": "#b4b8c5",
          tertiary: "#88d6af",
          "on-tertiary": "#003824",
          "tertiary-container": "#68b58f",
          "on-tertiary-container": "#00452d",
          error: "#ffb4ab",
          "on-error": "#690005",
          "error-container": "#93000a",
          "on-error-container": "#ffdad6",
          "primary-fixed": "#ffdea5",
          "primary-fixed-dim": "#e9c176",
          "on-primary-fixed": "#261900",
          "on-primary-fixed-variant": "#5d4201",
          "secondary-fixed": "#dee2f0",
          "secondary-fixed-dim": "#c2c6d4",
          "on-secondary-fixed": "#171c25",
          "on-secondary-fixed-variant": "#424752",
          "tertiary-fixed": "#a4f3ca",
          "tertiary-fixed-dim": "#88d6af",
          "on-tertiary-fixed": "#002113",
          "on-tertiary-fixed-variant": "#005236",
          background: "#111317",
          "on-background": "#e2e2e8",
          "surface-variant": "#333539",

          // Archival / Semantic accents & states
          bronze: "#c5a059",
          "bronze-hover": "#d4af37",
          "archival-bronze": "#c5a059",
          "archival-bronze-hover": "#d4af37",
          ochre: "#c5a059",
          "ochre-hover": "#d4af37",
          win: "#2e7d5b",
          loss: "#9e3b3b",
          draw: "#6c7485",

          // Surfaces & Dividers
          "canvas-base": "#0f1115",
          "surface-layer-1": "#14171e",
          "surface-layer-2": "#1a1f29",
          "border-base": "#1f242e",
          "border-interactive": "#282e3b",

          // Typography Tones
          "text-primary": "#faf8f5",
          "text-secondary": "#c8c5bd",
          "text-muted": "#7d8494",

          // Chessboard tokens
          "board-dark": "#282e3b",
          "board-light": "#e6e4df",
        },
      },
      fontFamily: {
        display: ["Newsreader", "Georgia", "serif"],
        body: ['"Hanken Grotesk"', "sans-serif"],
        sans: ['"Hanken Grotesk"', "sans-serif"],
        mono: ['"JetBrains Mono"', "monospace"],
        notation: ['"JetBrains Mono"', "monospace"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "400" }],
        "display-lg-mobile": ["34px", { lineHeight: "42px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "display-md": ["36px", { lineHeight: "44px", letterSpacing: "-0.015em", fontWeight: "400" }],
        "display-md-mobile": ["28px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "headline-lg": ["26px", { lineHeight: "34px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "headline-md": ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "500" }],
        "headline-sm": ["16px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "26px", letterSpacing: "0em", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "22px", letterSpacing: "0em", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "18px", letterSpacing: "0.005em", fontWeight: "400" }],
        "notation-md": ["14px", { lineHeight: "22px", letterSpacing: "-0.01em", fontWeight: "500" }],
        "notation-sm": ["12px", { lineHeight: "18px", letterSpacing: "0.02em", fontWeight: "400" }],
        "label-caps": ["11px", { lineHeight: "16px", letterSpacing: "0.08em", fontWeight: "600" }],
      },
      borderRadius: {
        sm: "0.125rem",
        DEFAULT: "0.25rem",
        md: "0.375rem",
        lg: "0.5rem",
        xl: "0.75rem",
        vault: "0.25rem",
      },
      spacing: {
        gutter: "1.5rem",
        margin: "2.5rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.75rem",
        "space-xl": "3rem",
      },
      maxWidth: {
        content: "1120px",
      },
    },
  },
  plugins: [],
};
