import { z } from "zod";
import {
  GameSchema,
  importGamesParams,
  searchGamesQuery,
  gameParams,
} from "../schemas/games.schema.js";
import type { PlatformType } from "../constants/platforms.js";

/**
 * Core domain representation of a game persisted in Chess Vault.
 *
 * @property id - Unique identifier generated by Chess Vault (MongoDB ObjectId string).
 * @property userId - ID of the user who owns this game record (Clerk User ID).
 * @property folderIds - Array of MongoDB folder ObjectIds this game belongs to, or `null` if unorganized.
 * @property platform - Source platform where the game was played (`"chess.com"` | `"lichess"`).
 * @property platformGameId - Unique game ID assigned by the original platform (e.g. Chess.com UUID or Lichess ID).
 * @property sourceUrl - Direct web link to view the game on the source platform.
 * @property title - Optional match title, formatted as `${whitePlayer.username} vs ${blackPlayer.username}` (or custom title).
 * @property whitePlayer - Details of the White player (`username` and rating).
 * @property blackPlayer - Details of the Black player (`username` and rating).
 * @property result - Outcome of the game (`"white"` | `"black"` | `"draw"`).
 * @property isRated - Whether the game was played as a rated match (`true`) or unrated (`false`).
 * @property timeClass - Standardized time control category (`"ultraBullet"` | `"bullet"` | `"blitz"` | `"rapid"` | `"classical"` | `"daily"` | `"correspondence"`).
 * @property playedAt - Timestamp when the game was completed on the original platform.
 * @property pgn - Full Portable Game Notation string including move sequence and headers.
 * @property notes - Optional user commentary or personal analysis (max 1000 chars).
 * @property tags - Optional custom tag for categorizing the game (max 20 chars).
 * @property createdAt - Timestamp when the record was persisted in Chess Vault.
 * @property updatedAt - Timestamp when the record was last modified in Chess Vault.
 */
export type Game = z.infer<typeof GameSchema>;

/**
 * Ingestion/normalization-stage game model produced after fetching and standardizing external platform data.
 *
 * Represents games before persistence in Chess Vault. Structurally identical to `Game`,
 * but omits database persistence metadata (`id`, `createdAt`, `updatedAt`).
 *
 * Data Lifecycle Flow:
 * `External Platform Data → normalize → NormalizedGame → persist → Game`
 */
export type NormalizedGame = Omit<Game, "id" | "createdAt" | "updatedAt">;
export type GameParams = z.infer<typeof gameParams>;


export interface ImportResult {
  success: boolean;
  message?: string;
}

export type ImportGameParams = {
  userId: string;
} & z.infer<typeof importGamesParams>;

export type ImportGamesParams = {
  userId: string;
  platform: PlatformType;
} & z.infer<typeof importGamesParams>;

export interface Chess_Com_Player {
  rating: number;
  result: string;
  "@id": string;
  username: string;
  uuid: string;
}

export type Chess_Com_Game = {
  url: string;
  pgn: string;
  time_control: string;
  end_time: number;
  rated: boolean;
  tcn: string;
  uuid: string;
  initial_setup: string;
  fen: string;
  time_class: string;
  rules: string;
  white: Chess_Com_Player;
  black: Chess_Com_Player;
  eco?: string;
};

export interface Lichess_Player {
  user?: {
    id: string;
    name: string;
  };
  rating?: number;
  ratingDiff?: number;
  aiLevel?: number;
}

export interface Lichess_Game {
  id: string;
  rated: boolean;

  variant: string;
  speed: string;
  perf: string;

  createdAt: number;
  lastMoveAt: number;

  status: string;
  source: string;

  winner?: "white" | "black";

  players: {
    white: Lichess_Player;
    black: Lichess_Player;
  };

  moves: string;
  pgn: string;

  clock?: {
    initial: number;
    increment: number;
    totalTime: number;
  };
}

export type GameSearchParams = z.infer<typeof searchGamesQuery> & {
  userId: string;
};
